//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collector._Helpers._Translations {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_pt {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_pt() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Collector._Helpers._Translations.AppResources.pt", typeof(AppResources_pt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        internal static string PleaseEnterYourCredentials {
            get {
                return ResourceManager.GetString("PleaseEnterYourCredentials", resourceCulture);
            }
        }
        
        internal static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        internal static string TypeYourEmail {
            get {
                return ResourceManager.GetString("TypeYourEmail", resourceCulture);
            }
        }
        
        internal static string TypeYourPassword {
            get {
                return ResourceManager.GetString("TypeYourPassword", resourceCulture);
            }
        }
        
        internal static string OrLoginWith {
            get {
                return ResourceManager.GetString("OrLoginWith", resourceCulture);
            }
        }
        
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        internal static string Materials {
            get {
                return ResourceManager.GetString("Materials", resourceCulture);
            }
        }
        
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        internal static string SingOut {
            get {
                return ResourceManager.GetString("SingOut", resourceCulture);
            }
        }
        
        internal static string YourDescription {
            get {
                return ResourceManager.GetString("YourDescription", resourceCulture);
            }
        }
        
        internal static string YourStory {
            get {
                return ResourceManager.GetString("YourStory", resourceCulture);
            }
        }
        
        internal static string WhoWeAre {
            get {
                return ResourceManager.GetString("WhoWeAre", resourceCulture);
            }
        }
        
        internal static string WhereAreWeGoing {
            get {
                return ResourceManager.GetString("WhereAreWeGoing", resourceCulture);
            }
        }
        
        internal static string Collaborate {
            get {
                return ResourceManager.GetString("Collaborate", resourceCulture);
            }
        }
        
        internal static string Collectors {
            get {
                return ResourceManager.GetString("Collectors", resourceCulture);
            }
        }
        
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        internal static string MyHistory {
            get {
                return ResourceManager.GetString("MyHistory", resourceCulture);
            }
        }
        
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        internal static string PaperTitle {
            get {
                return ResourceManager.GetString("PaperTitle", resourceCulture);
            }
        }
        
        internal static string PaperSubTitle {
            get {
                return ResourceManager.GetString("PaperSubTitle", resourceCulture);
            }
        }
        
        internal static string PaperText {
            get {
                return ResourceManager.GetString("PaperText", resourceCulture);
            }
        }
        
        internal static string AluminumTitle {
            get {
                return ResourceManager.GetString("AluminumTitle", resourceCulture);
            }
        }
        
        internal static string AluminumSubTitle {
            get {
                return ResourceManager.GetString("AluminumSubTitle", resourceCulture);
            }
        }
        
        internal static string AluminumText {
            get {
                return ResourceManager.GetString("AluminumText", resourceCulture);
            }
        }
        
        internal static string PlasticTitle {
            get {
                return ResourceManager.GetString("PlasticTitle", resourceCulture);
            }
        }
        
        internal static string PlasticSubTitle {
            get {
                return ResourceManager.GetString("PlasticSubTitle", resourceCulture);
            }
        }
        
        internal static string PlasticText {
            get {
                return ResourceManager.GetString("PlasticText", resourceCulture);
            }
        }
        
        internal static string OilTitle {
            get {
                return ResourceManager.GetString("OilTitle", resourceCulture);
            }
        }
        
        internal static string OilSubTitle {
            get {
                return ResourceManager.GetString("OilSubTitle", resourceCulture);
            }
        }
        
        internal static string OilText {
            get {
                return ResourceManager.GetString("OilText", resourceCulture);
            }
        }
        
        internal static string DiverseTitle {
            get {
                return ResourceManager.GetString("DiverseTitle", resourceCulture);
            }
        }
        
        internal static string DiverseSubTitle {
            get {
                return ResourceManager.GetString("DiverseSubTitle", resourceCulture);
            }
        }
        
        internal static string DiverseText {
            get {
                return ResourceManager.GetString("DiverseText", resourceCulture);
            }
        }
        
        internal static string MetalTitle {
            get {
                return ResourceManager.GetString("MetalTitle", resourceCulture);
            }
        }
        
        internal static string MetalSubTitle {
            get {
                return ResourceManager.GetString("MetalSubTitle", resourceCulture);
            }
        }
        
        internal static string MetalText {
            get {
                return ResourceManager.GetString("MetalText", resourceCulture);
            }
        }
        
        internal static string TreePruningTitle {
            get {
                return ResourceManager.GetString("TreePruningTitle", resourceCulture);
            }
        }
        
        internal static string TreePruningSubTitle {
            get {
                return ResourceManager.GetString("TreePruningSubTitle", resourceCulture);
            }
        }
        
        internal static string TreePruningText {
            get {
                return ResourceManager.GetString("TreePruningText", resourceCulture);
            }
        }
        
        internal static string FurnitureTitle {
            get {
                return ResourceManager.GetString("FurnitureTitle", resourceCulture);
            }
        }
        
        internal static string FurnitureSubTitle {
            get {
                return ResourceManager.GetString("FurnitureSubTitle", resourceCulture);
            }
        }
        
        internal static string FurnitureText {
            get {
                return ResourceManager.GetString("FurnitureText", resourceCulture);
            }
        }
        
        internal static string ElectronicsTitle {
            get {
                return ResourceManager.GetString("ElectronicsTitle", resourceCulture);
            }
        }
        
        internal static string ElectronicsSubTitle {
            get {
                return ResourceManager.GetString("ElectronicsSubTitle", resourceCulture);
            }
        }
        
        internal static string ElectronicsText {
            get {
                return ResourceManager.GetString("ElectronicsText", resourceCulture);
            }
        }
        
        internal static string RubbleTitle {
            get {
                return ResourceManager.GetString("RubbleTitle", resourceCulture);
            }
        }
        
        internal static string RubbleSubTitle {
            get {
                return ResourceManager.GetString("RubbleSubTitle", resourceCulture);
            }
        }
        
        internal static string RubbleText {
            get {
                return ResourceManager.GetString("RubbleText", resourceCulture);
            }
        }
        
        internal static string GlassTitle {
            get {
                return ResourceManager.GetString("GlassTitle", resourceCulture);
            }
        }
        
        internal static string GlassSubTitle {
            get {
                return ResourceManager.GetString("GlassSubTitle", resourceCulture);
            }
        }
        
        internal static string GlassText {
            get {
                return ResourceManager.GetString("GlassText", resourceCulture);
            }
        }
        
        internal static string BatteryTitle {
            get {
                return ResourceManager.GetString("BatteryTitle", resourceCulture);
            }
        }
        
        internal static string BatterySubTitle {
            get {
                return ResourceManager.GetString("BatterySubTitle", resourceCulture);
            }
        }
        
        internal static string BatteryText {
            get {
                return ResourceManager.GetString("BatteryText", resourceCulture);
            }
        }
    }
}
